version: "3.8"
services:
  reactapp:
    build: ./reactapp
    container_name: reactapp
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  postgres:
   image: 'postgres:latest'
   environment:
     - POSTGRES_PASSWORD=postgres_password
